sudo: required
dist: xenial

language: python
python:
  - "3.7"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test;'

install:
  - cd ./server/src
  - openssl genrsa -out jwtRS256.key 2048
  - openssl rsa -in jwtRS256.key -outform PEM -out jwtRS256.key.pub
  - pip install -r requirements.txt

script:
  - pytest