sudo: required
dist: xenial

language: python
python:
  - "3.7"

services:
  - mysql


install:
  - openssl genrsa -out server/jwtRS256.key 2048
  - openssl rsa -in server/jwtRS256.key -pubout -outform PEM -out server/jwtRS256.key.pub
  - pip install -r server/requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install tox-travis

script:
  - python server/init_db.py
  - make test-server

after_success:
  - coveralls